apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-spring-deployment
spec:
  selector:
    matchLabels:
      app: faniverse-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: faniverse-backend
    spec:
      containers: 
        - name: faniverse-con
          image: yejin20211130/faniverse:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef: 
                name: faniverse-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: devops-spring-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: faniverse-backend
